rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - ree
after_script:  
  - "sh -c 'cd test/dummy && bundle exec rake db:create db:migrate db:test:prepare'"
before_script: 
  - "sh -c 'cd test/dummy && bundle exec rake db:create db:migrate db:test:prepare'"