rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby
gemfile:
  - gemfiles/4.0.5.gemfile
  - gemfiles/4.1.1.gemfile
script:
  - "sudo apt-get install -qq lame"
  - "sh -c 'cd test/dummy && bundle exec rake db:create db:migrate db:test:prepare'"
  - "bundle exec rake test"
addons:
  code_climate:
    repo_token: 
      secure: UwfHvYfl01m73ewViv5FCoXhFQQsICDtAlBYUS4wa3DzNicfTJAk08BvL3vQncXxcY6zyKTr+dYa225MaWZeAJO9YvlUcJs6cFAVXYW7gaLQb7V34MbrGiH6cCVt6zjwj/RTMyEO3iURGkXxbTb8mHtK+h+M51Z9reZUQScMtdg=